### ISSUE TITLE
[BUG] Integration tests are failing in dependabot PRs

### ISSUE THREAD

**Issue by dblock** [opensearch-project/opensearch-sdk-py#194]
### What is the bug?

CI/CD got stale, integration tests are failing in Dependabot PRs.

### How can one reproduce the bug?

See failures in any of https://github.com/opensearch-project/opensearch-sdk-py/pulls.

### What is the expected behavior?

CI/CD to be green.

**Comment by dbwiddis** [comment]
> CI/CD got stale

OpenSearch is not even compiling.  
```
FAILURE: Build completed with 2 failures.
> Task :server:compileJava FAILED
...
> Compilation failed; see the compiler error output for details.
```
Looks like it's set for strict javadoc checking
```
/home/runner/work/opensearch-sdk-py/opensearch-sdk-py/opensearch/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java:48: error: no tag name after @
     * Utility method to get list of indices filtered as per {@param filterPredicate} and the sorted according to {@param comparator}.
                                                             ^
/home/runner/work/opensearch-sdk-py/opensearch-sdk-py/opensearch/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java:48: error: no tag name after @
     * Utility method to get list of indices filtered as per {@param filterPredicate} and the sorted according to {@param comparator}.
                                                                                                                  ^
/home/runner/work/opensearch-sdk-py/opensearch-sdk-py/opensearch/server/src/main/java/org/opensearch/action/pagination/PaginationStrategy.java:60: error: no tag name after @
     * Utility method to get list of indices sorted as per {@param comparator}.
```
Those `@param` should probably be `@link`.

We may be able to work around it by adding `-x javadoc` to the gradle build until the above is fixed.

**Comment by dbwiddis** [comment]
This should fix 1 of 2 problems:
 - https://github.com/opensearch-project/OpenSearch/issues/16374

Other possible problem is Gradle-9 incompatible features, we can add a switch to our gradle command in CI to not fail on deprecation.  Let's get the java one fixed first.

**Comment by dbwiddis** [comment]
We should also use Java 17 in our integration GHA.
