### ISSUE TITLE
[FEATURE] Create sample CRUD extension

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-py#55]
### Is your feature request related to a problem?

Hello World is great to introduce the simplicity of extensions, but users want to know how to interact with the OpenSearch cluster.  A sample demonstrating basic CRUD operations on an index will demonstrate that.

### What solution would you like?

The process of creating a CRUD extension in Java is documented [here](https://github.com/opensearch-project/opensearch-sdk-java/blob/main/CREATE_YOUR_FIRST_EXTENSION.md) and implemented on my account [here](https://github.com/dbwiddis/crudextension).  Similar documentation should be provided on this site, with a sample implementation in the samples folder.

**Comment by Jatin-tec** [comment]
I would like to work on this. Could you please assign it to me?

**Comment by dbwiddis** [comment]
Absolutely, @Jatin-tec!   Let me know if you have any questions!

**Comment by Jatin-tec** [comment]
should I add CRUD extension documentation in root or inside samples folder (in CRUDExtension folder).

**Comment by dbwiddis** [comment]
In the CRUDExtension folder under samples, similar to https://github.com/opensearch-project/opensearch-sdk-py/tree/main/samples/hello

**Comment by Jatin-tec** [comment]
I'm facing trouble translating the Java-based documentation and code into Python. While I understand the logic, I am struggling with identifying the appropriate Python libraries for the SDK implementation.
I have set up OpenSearch locally using Docker and am keen to contribute. However, my unfamiliarity with Java and the lack of Python-specific examples are hindering my progress. I am aware of Flask, but I believe it might not align perfectly with the purpose of this issue.

**Comment by dbwiddis** [comment]
> identifying the appropriate Python libraries for the SDK implementation.

You should only need `opensearch-py` client.  The imports in the Java SDK are associated with the request/response classes which we have implemented separately here.

I'd suggest going through the examples in the opensearch-py documentation: https://github.com/opensearch-project/opensearch-py/blob/main/USER_GUIDE.md

**Comment by Jatin-tec** [comment]
Thank you so much for your help, @dbwiddis ! I learned a lot while making this contribution, and you were incredibly supportive. I'm just one step away from submitting my PR. In the case of a POST request, how do I fetch the body from the ExtensionRestRequest?

```
class ExtensionRestRequest(TransportRequest):
    def __init__(
        self,
        method: RestMethod = None,
        uri: str = "",
        path: str = "",
        params: dict[str, str] = dict(),
        headers: dict[str, list[str]] = dict(),
        media_type: str = "",
        content: bytes = b"",
        principal_identifier_token: str = "",
        http_version: HttpVersion = None,
    )
```

**Comment by dbwiddis** [comment]
Glad to hear and happy to help!

> how do I fetch the body from the ExtensionRestRequest?

The body will be in the bytes in the `content` field, with its corresponding `media_type` (e.g.., `application/json`) indicating how it should be parsed.

I don't think we have any JSON parsing utils written, so feel free to find an appropriate dependency for that.

One gotcha that you might encounter is consumed params and content, see https://github.com/opensearch-project/opensearch-sdk-py/issues/49 .  For the three APIs with `{id}` in the URI, you'll need to indicate in the response that you "consumed" the "id" parameter.  For now you'll just need to add that "id" string to the `consumed_params` list in the response.  (For completeness you can also set `content_consumed` to true when you read the content, although I don't think anything will break if you don't.)

**Comment by Jatin-tec** [comment]
Thanks a ton.

> One gotcha that you might encounter is consumed params and content, see https://github.com/opensearch-project/opensearch-sdk-py/issues/49 . For the three APIs with {id} in the URI, you'll need to indicate in the response that you "consumed" the "id" parameter. For now you'll just need to add that "id" string to the consumed_params list in the response. (For completeness you can also set content_consumed to true when you read the content, although I don't think anything will break if you don't.)
>
You saved me! 
Everything's working smoothly now. I'll be working on completing the documentation and will create the PR soon. 
Appreciate your help!

**Comment by dbwiddis** [comment]
So I'm curious how you got it working if https://github.com/opensearch-project/opensearch-sdk-py/issues/45 is still a bug. :)

**Comment by Jatin-tec** [comment]
I created same path for all operations (different method types)
```
NamedRoute(method=RestMethod.POST, path="/crud", unique_name="crud_post"),
                NamedRoute(method=RestMethod.GET, path="/crud", unique_name="crud_get"),
                NamedRoute(method=RestMethod.PUT, path="/crud", unique_name="crud_put"),
                NamedRoute(method=RestMethod.DELETE, path="/crud", unique_name="crud_delete")
```
then I'm querying `id` from request.params like this `id = request.params.get('id')` 

example PUT request :
```
curl -XPUT "localhost:9200/_extensions/_crud-py/crud?id=gDTedIsBNJHV14IHbeqe" -H "Content-Type:application/json" --data '{
  "title": "Moneyball",
  "director": "Bennett Miller",
  "year": "2011",
  "rating": "PG-13"
}'
```
