### ISSUE TITLE
[BUG] StreamInput integer types are unsigned

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-py#88]
### What is the bug?

The `read_byte()`, `read_short()`, `read_int()`, and `read_long()` methods in `StreamInput` return unsigned integers.

### How can one reproduce the bug?

Attempt to deserialize any value with a negative sign bit, for example
```py
input = StreamInput(b"\xff")
self.assertEqual(input.read_byte(), -1)
```
> AssertionError: 255 != -1

```py
input = StreamInput(b"\xff\xff\xff\xff\")
self.assertEqual(input.read_int(), -1)
```
> AssertionError: 4294967295 != -1

### What is the expected behavior?

Python `int` value matches the signed Java value from OpenSearch

### Do you have any additional context?

![image](https://github.com/opensearch-project/opensearch-sdk-py/assets/9291703/4d665dc6-fd8b-42fe-a94b-a62750136165)

**Comment by dblock** [comment]
(1) works for me. Do you have an an XKCD for (2) and (3)?

**Comment by dbwiddis** [comment]
> (1) works for me. Do you have an an XKCD for (2) and (3)?

2:
![image](https://github.com/opensearch-project/opensearch-sdk-py/assets/9291703/70cf8f2d-01f6-4e95-9468-644446037fd5)

3: 
![image](https://github.com/opensearch-project/opensearch-sdk-py/assets/9291703/08d38581-2297-439c-957f-77b413f899d9)

**Comment by dbwiddis** [comment]
Bonus, the `int.from_bytes()` approach is so much better than this mess:
```python
def read_int(self) -> int:
    return ((self.read_byte() & 0xFF) << 24) | ((self.read_byte() & 0xFF) << 16) | ((self.read_byte() & 0xFF) << 8) | (self.read_byte() & 0xFF)

def read_long(self) -> int:
    return self.read_int() << 32 | self.read_int() & 0xFFFFFFFF
```
