### ISSUE TITLE
[FEATURE] Single line formatting script

### ISSUE THREAD

**Issue by dbwiddis** [opensearch-project/opensearch-sdk-py#9]
### Is your feature request related to a problem?

The Developer Guide specifies multiple commands to format code (isort, black, autoflake) and check formatting (flake8).  These are hard to remember, particularly with the required arguments, and require copy-paste or bash buffer scrollback.

### What solution would you like?

A single easy-to-remember command I can type to execute a script in bash or, hey, even python, that does all the formatting steps.   Equivalent of `mvn spotless:apply` or `gradle spotlessApply` except it's not spotless.   A script named `format` might work.

### What alternatives have you considered?

 - Continuing to copy-paste from the Dev Guide.
 - Creating my own script
 - Creating alias(is) in my .zshrc
 - Finding some product out there that eases this process, like [Bashy](https://github.com/zeppaman/bashy)

**Comment by dblock** [comment]
Usually this is done with pre-commit config: https://github.com/opensearch-project/opensearch-build/blob/main/.pre-commit-config.yaml, but we can also add a script.

**Comment by dbwiddis** [comment]
> Usually this is done with pre-commit config

Assuming I have directions somewhere how to use that, that works!
